on:
  push:
    tags:
      - "v*"

name: Create and upload releases

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.4"
      - name: Test code format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not well formatted"
            gofmt -d .
            exit 1
          fi
      - name: Install dependencies
        run: go get ./...
      - name: Test
        run: go test ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.4"
      - name: Build Go code
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          GOOS=linux GOARCH=386 go build -o demonstracao-finaceira-bacen-json-386 -ldflags "-X 'github.com/oliveirafilipe/demonstracao-finaceira-bacen-json/metadata.Version=${TAG}'"
          GOOS=windows GOARCH=386 go build -o demonstracao-finaceira-bacen-json-386.exe -ldflags "-X 'github.com/oliveirafilipe/demonstracao-finaceira-bacen-json/metadata.Version=${TAG}'"
          GOOS=darwin GOARCH=amd64 go build -o demonstracao-finaceira-bacen-json-macos-amd64 -ldflags "-X 'github.com/oliveirafilipe/demonstracao-finaceira-bacen-json/metadata.Version=${TAG}'"
      - name: Upload release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          hub release create \
            -a demonstracao-finaceira-bacen-json-386 \
            -a demonstracao-finaceira-bacen-json-386.exe \
            -a demonstracao-finaceira-bacen-json-macos-amd64 \
            -m "${TAG}" "${TAG}"
