name: "Test"

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.20.4"
      - name: Test code format
        run: |
          if [ -n "$(gofmt -l .)" ]; then
            echo "Go code is not well formatted"
            gofmt -d .
            exit 1
          fi
      - name: Install dependencies
        run: go get ./...
      - name: Test
        run: go test ./...
